resources:
- name: repo
  type: git
  icon: github-circle
  source:
    branch: master
    uri: https://github.com/cappyzawa/version-hitory-test
- name: image
  type: docker-image
  icon: docker
  source:
    repository: cappyzawa/alpine
    username: cappyzawa
    password: ((docker-hub-password))

jobs:
- name: push-1
  plan:
  - get: repo
    trigger: true
  - put: image
    params:
      build: repo
- name: push-2
  plan:
  - in_parallel:
    - get: repo
    - get: image
      trigger: true
      passed:
      - push-1
      params:
        save: false
  - put: image
    params:
      build: repo
